# Copyright 2023 The Tongsuo Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://github.com/Tongsuo-Project/tongsuo-mini/blob/main/LICENSE

name: GitHub CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: clang-format check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '17'
        include-regex: '^\./(app|examples|include|perf|src|test)/.*\.(c|h)$'
  minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        python3 -m venv ${{github.workspace}}/.venv
        source ${{github.workspace}}/.venv/bin/activate
        pip3 install -r ${{github.workspace}}/test/requirements.txt
        ctest -C ${{env.BUILD_TYPE}}
    - name: debug
      if: ${{ failure() }}
      run: |
        cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log

  with_single_module:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [ascon, asn1, hmac, oscore, sm3, sm4]
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_${{matrix.module}}=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        python3 -m venv ${{github.workspace}}/.venv
        source ${{github.workspace}}/.venv/bin/activate
        pip3 install -r ${{github.workspace}}/test/requirements.txt
        ctest -C ${{env.BUILD_TYPE}}
    - name: debug
      if: ${{ failure() }}
      run: |
        cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log

  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DWITH_ALL=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        python3 -m venv ${{github.workspace}}/.venv
        source ${{github.workspace}}/.venv/bin/activate
        pip3 install -r ${{github.workspace}}/test/requirements.txt
        ctest -C ${{env.BUILD_TYPE}}
    - name: debug
      if: ${{ failure() }}
      run: |
        cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log

